name: Testing
on: push
jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring
        coverage: xdebug #optional

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist

    - name: Run Tests
      run: |
        php vendor/bin/phpunit --coverage-clover=clover-report.${{ matrix.php-versions }}.xml

    - name: codecoverage
      uses: pleo-io/actions/codecov@v1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        args: -f clover-report.${{ matrix.php-versions }}.xml -F ${{ matrix.php-versions }}
